service:
  type: ClusterIP
  port: 8070
  image: arperinn/reservation-service:latest
  env:
    DATA_BASE_PORT: 5432
    DATA_BASE_NAME: postgres
    DATA_BASE_USER: postgres
    DATA_BASE_PASS: postgres
    DATA_BASE_HOST: postgres